ampOn = [[ASCII:
.....1a..........AC..........E
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3.........t...q....
5..........c.........s........
......6.......................
.........................q....
.....5c..............s...t....
]]

ampOff = [[ASCII:
.....1a.....x....AC.y.......zE
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3.........t...q....
5..........c.........s........
......6.......................
.........................q....
...x.5c....y.......z.s...t....
]]

local module = {}

local function setIcon(state)
  module.menu:setIcon(state and ampOn or ampOff)
end

module.menu = hs.menubar.new()
module.menu:setClickCallback(function() setIcon(hs.caffeinate.toggle("displayIdle")) end)
setIcon(hs.caffeinate.get("displayIdle"))

return module

-- Toggleable menubar icon that stops the screen from going off, like KeepingYouAwake
-- From https://gist.github.com/heptal/50998f66de5aba955c00
