# chezmoi:template:left-delimiter="# [[" right-delimiter=]]

# [[ $rustOs := .chezmoi.os ]]
# [[ if eq $rustOs "darwin" ]]
# [[ $rustOs = "apple-darwin" ]]
# [[ else if eq $rustOs "linux" ]]
# [[ $rustOs = "unknown-linux-gnu" ]]
# [[ end ]]

# [[ $altArch := .chezmoi.arch ]]
# [[ if eq $altArch "amd64" ]]
# [[ $altArch = "x86_64" ]]
# [[ else if eq $altArch "arm64" ]]
# [[ $altArch = "aarch64" ]]
# [[ end ]]

".oh-my-zsh":
  type: "git-repo"
  url: "https://github.com/ohmyzsh/ohmyzsh.git"
  exact: true
  refreshPeriod: "168h"
".oh-my-zsh_custom/plugins/zsh-syntax-highlighting":
  type: "git-repo"
  exact: true
  url: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
  refreshPeriod: "168h"
".oh-my-zsh_custom/plugins/zsh-autosuggestions":
  type: "git-repo"
  exact: true
  url: "https://github.com/zsh-users/zsh-autosuggestions.git"
  refreshPeriod: "168h"
".oh-my-zsh_custom/plugins/auto-notify":
  type: "git-repo"
  exact: true
  url: "https://github.com/MichaelAquilina/zsh-auto-notify.git"
  refreshPeriod: "168h"
".local/bin/aws_finder":
  type: "file"
  url: # [[ gitHubReleaseAssetURL "wjam/aws_finder" "v0.7.2" (printf "aws_finder-%s-%s" .chezmoi.os .chezmoi.arch) | quote ]]
  executable: true
".vim/pack/editorconfig/start":
  type: "git-repo"
  exact: true
  url: "https://github.com/editorconfig/editorconfig-vim.git"
  refreshPeriod: "168h"
".vim/pack/polyglot/start/vim-polyglot":
  type: "git-repo"
  exact: true
  url: "https://github.com/sheerun/vim-polyglot.git"
  refreshPeriod: "168h"
".local/bin/rustup-init":
  type: "file"
  url: "https://static.rust-lang.org/rustup/dist/# [[ $altArch ]]-# [[ $rustOs ]]/rustup-init"
  executable: true
# [[- if and (eq .chezmoi.os "linux") .gui ]]
".local/bin/FreeCAD.AppImage":
  type: "file"
  url: # [[ gitHubReleaseAssetURL "FreeCAD/FreeCAD" "1.0.1" "FreeCAD_*-conda-Linux-x86_64-py311.AppImage" | quote ]]
  executable: true
".local/bin/BambuStudio.AppImage":
  type: "file"
  url: # [[ gitHubReleaseAssetURL "bambulab/BambuStudio" "v01.08.04.51" "BambuStudio_linux_ubuntu_*.AppImage" | quote ]]
  executable: true
".local/bin/OpenSCAD.AppImage":
  type: "file"
  url: # [[ gitHubReleaseAssetURL "openscad/openscad" "openscad-2021.01" "OpenSCAD-*-x86_64.AppImage" | quote ]]
  executable: true
".local/bin/Obsidian.AppImage":
  type: "file"
  url: # [[ gitHubReleaseAssetURL "obsidianmd/obsidian-releases" "v1.10.6" "Obsidian-1.10.6.AppImage" | quote ]]
  executable: true
# [[- end ]]
