[".oh-my-zsh"]
  type = "git-repo"
  url = "https://github.com/ohmyzsh/ohmyzsh.git"
  exact = true
  refreshPeriod = "168h"
[".oh-my-zsh_custom/plugins/zsh-syntax-highlighting"]
  type = "git-repo"
  exact = true
  url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
  refreshPeriod = "168h"
[".oh-my-zsh_custom/plugins/zsh-autosuggestions"]
  type = "git-repo"
  exact = true
  url = "https://github.com/zsh-users/zsh-autosuggestions.git"
  refreshPeriod = "168h"
[".oh-my-zsh_custom/plugins/auto-notify"]
  type = "git-repo"
  exact = true
  url = "https://github.com/MichaelAquilina/zsh-auto-notify.git"
  refreshPeriod = "168h"
[".docker/cli-plugins/docker-buildx"]
  type = "file"
  url = "https://github.com/docker/buildx/releases/download/v0.10.4/buildx-v0.10.4.{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
  executable = true
[".docker/cli-plugins/docker-compose"]
  type = 'file'
  url = 'https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-{{ .chezmoi.os }}-{{ if eq .chezmoi.arch "amd64" }}x86_64{{ else if eq .chezmoi.arch "arm64" }}aarch64{{ else }}{{ .chezmoi.arch }}{{ end }}'
  executable = true
[".local/bin/aws_finder"]
  type = "file"
  url = "https://github.com/wjam/aws_finder/releases/download/v0.6.3/aws_finder-{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
  executable = true
[".vim/pack/editorconfig/start"]
  type = "git-repo"
  url = "https://github.com/editorconfig/editorconfig-vim.git"
  refreshPeriod = "168h"
[".vim/pack/polyglot/start/vim-polyglot"]
  type = "git-repo"
  url = "https://github.com/sheerun/vim-polyglot.git"
  refreshPeriod = "168h"
