# Contents of this file drives installation of software
# .chezmoiscripts/run_onchange_before_brew-install.sh.tmpl
# .chezmoiscripts/run_onchange_before_apt-install.sh.tmpl
[all_os]
brews = [
  "go",
  "fzf", # Used by the ZSH history plugin as well executable_jq-interactive
  "dive",
  "jq",
  "git",
  "htop",
  "tree",
  "curl",
  "direnv",
  "pandoc", # Transform markdown to man pages and other formats
  "ipcalc",
  "powerline-go",
  "terraform",
  "terragrunt",
  "packer",
  "kubernetes-cli",
  "kubectx", # Easily switch k8s contexts
  "stern", # Displays k8s pod logs better
  "k9s",
  "vault",
  "chezmoi",
  "helm",
  "pv", # Can be used to write scripts for a demo that don't touch the internet (e.g. `cat output.txt | pv --quiet --line-mode --rate-limit 5`)
  "rustup-init", # Manage rust
  "tealdeer", # Give examples of how to use commands
]
full_brews = [
  "awscli",
  "azure-cli",
  "openjdk@17",
  "pgcli", # PostgreSQL CLI
  "colima", # Utility to manage local Docker & Kubernetes VMs
  "docker", # Command line only
]
taps = [
]

[mac_os]
brews = [
  "bash-completion",
  "readline", # .inputrc
  "watch",
  "blueutil", # used by Hammerspoon scripts
]
taps = [
  "wez/wezterm",
]
casks = [
  "hammerspoon",
  "stats",
  "firefox",
  "google-chrome",
  "visual-studio-code",
  "jetbrains-toolbox",
  "wez/wezterm/wezterm",
  # TODO Temporarily needed until https://github.com/Homebrew/homebrew-core/pull/97394
  # Re-add `"dockutil"` to brews list when merged
  "hpedrorodrigues/tools/dockutil",
  "obs", # Needed to control webcam
]
full_casks = [
  "google-cloud-sdk",
  "drawio",
  "libreoffice",
  "gimp",
  "inkscape",
  "slack",
]

[mac_os_admin]
full_brews = [
  "mas", # mas needs admin permissions depending on what it installs
]
full_casks = [
]

[linux_os_admin]
full_brews = [
  "wezterm",
]
taps = [
  "wez/wezterm-linuxbrew",
]
debs = [
  "curl",
  "git",
  "gnome-tweaks",
  "wl-clipboard",
  "zsh",
  "apt-transport-https", # needed to install vscode - https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions
  "code",
  "build-essential",
  "rclone",
  "vim-runtime",
  "vim-gui-common",
]
full_debs = [
]
