# chezmoi:template:left-delimiter="# [[" right-delimiter=]]

# [[ $rustOs := .chezmoi.os ]]
# [[ if eq $rustOs "darwin" ]]
# [[ $rustOs = "apple-darwin" ]]
# [[ else if eq $rustOs "linux" ]]
# [[ $rustOs = "unknown-linux-gnu" ]]
# [[ end ]]

# [[ $altArch := .chezmoi.arch ]]
# [[ if eq $altArch "amd64" ]]
# [[ $altArch = "x86_64" ]]
# [[ else if eq $altArch "arm64" ]]
# [[ $altArch = "aarch64" ]]
# [[ end ]]

".oh-my-zsh":
  type: "git-repo"
  url: "https://github.com/ohmyzsh/ohmyzsh.git"
  exact: true
  refreshPeriod: "168h"
".oh-my-zsh_custom/plugins/zsh-syntax-highlighting":
  type: "git-repo"
  exact: true
  url: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
  refreshPeriod: "168h"
".oh-my-zsh_custom/plugins/zsh-autosuggestions":
  type: "git-repo"
  exact: true
  url: "https://github.com/zsh-users/zsh-autosuggestions.git"
  refreshPeriod: "168h"
".oh-my-zsh_custom/plugins/auto-notify":
  type: "git-repo"
  exact: true
  url: "https://github.com/MichaelAquilina/zsh-auto-notify.git"
  refreshPeriod: "168h"
".local/bin/aws_finder":
  type: "file"
  url: "https://github.com/wjam/aws_finder/releases/download/v0.7.2/aws_finder-# [[ .chezmoi.os ]]-# [[ .chezmoi.arch ]]"
  executable: true
".vim/pack/editorconfig/start":
  type: "git-repo"
  exact: true
  url: "https://github.com/editorconfig/editorconfig-vim.git"
  refreshPeriod: "168h"
".vim/pack/polyglot/start/vim-polyglot":
  type: "git-repo"
  exact: true
  url: "https://github.com/sheerun/vim-polyglot.git"
  refreshPeriod: "168h"
".local/bin/rustup-init":
  type: "file"
  url: "https://static.rust-lang.org/rustup/dist/# [[ $altArch ]]-# [[ $rustOs ]]/rustup-init"
  executable: true
# [[- if and (eq .chezmoi.os "linux") .gui ]]
".local/bin/FreeCAD.AppImage":
  type: "file"
  url: "https://github.com/FreeCAD/FreeCAD/releases/download/1.0.1/FreeCAD_1.0.1-conda-Linux-x86_64-py311.AppImage"
  executable: true
".local/bin/BambuStudio.AppImage":
  type: "file"
  url: "https://github.com/bambulab/BambuStudio/releases/download/v01.08.04.51/BambuStudio_linux_ubuntu_v01.08.04.51_20240117.AppImage"
  executable: true
".local/bin/OpenSCAD.AppImage":
  type: "file"
  url: "https://github.com/openscad/openscad/releases/download/openscad-2021.01/OpenSCAD-2021.01-x86_64.AppImage"
  executable: true
".local/bin/Obsidian.AppImage":
  type: "file"
  url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.8.4/Obsidian-1.8.4.AppImage"
  executable: true
# [[- end ]]
