name: CI
permissions:
  contents: read

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

concurrency: # Avoid needlessly continuing to run the workflow if it's already been superseded
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate GitHub Actions
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: 'false'

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          advanced-security: 'false'
          persona: auditor
          annotations: 'true'

  test:
    name: Test
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md
    # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-24.04", "macos-26"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: 'false'

      - name: Link to correct location
        run: |
          mkdir -p $HOME/.local/share
          ln -s $GITHUB_WORKSPACE $HOME/.local/share/chezmoi

      - name: Clean up GitHub
        run: .github/clean-up-mac.sh
        if: runner.os == 'macOS'

      - name: Test
        env:
          CHEZMOI_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./testing.sh --promptBool "Access to app store? y or n:"=n --promptBool "Have admin access? y or n:"=y,"Install everything? y or n:"=n --promptString "Email address for Git:"=ci@example.test --promptString "Use another user to run brew install:"=

  dependabot:
    needs:
      - test
      - validate
    name: Auto-merge dependabot PRs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Required to automatically merge PR
      contents: write # Required to automatically merge PR
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
