name: CI
permissions:
  contents: read

on: [push]

jobs:
  test:

    #   https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
    #   https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-22.04", "macos-12"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Link to correct location
        run: |
          mkdir -p $HOME/.local/share
          ln -s $GITHUB_WORKSPACE $HOME/.local/share/chezmoi
      - name: Clean up GitHub
        run: |
          command -v brew && brew list go && brew uninstall go
          rm /usr/local/bin/go || true
          rm /usr/local/bin/gofmt || true
          command -v brew && brew list python@3.11 && brew uninstall --ignore-dependencies python@3.11
          rm /usr/local/bin/2to3{,-3.11} || true
          rm /usr/local/bin/{idle,pydoc}{3,3.11} || true
          rm /usr/local/bin/{python3,python3.11}{,-config} || true
        if: runner.os == 'macOS'
      - name: Test
        run: ./testing.sh --promptBool "Access to app store? y or n:"=n --promptBool "Have admin access? y or n:"=y,"Install everything? y or n:"=n --promptString "Email address for Git:"=ci@example.test

  dependabot:
    needs:
      - test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
